version: '3.7'
services:
  scrapper:
    container_name: scrapper
    build:
      context: ../services/scrapper
      dockerfile: Dockerfile
    restart: never
    deploy:
      resources:
          limits:
            cpus: "1"
            memory: 150M
      replicas: 1
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    networks:
      - scraps
    volumes:
      - ../data/scrapper:/usr/app/data
  api:
    container_name: api
    build:
      context: ../services/api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always
    deploy:
      resources:
          limits:
            cpus: "1"
            # app will crash if enough memory is not provided
            # memory: 150M
      replicas: 1
      restart_policy:
        max_attempts: 3
        condition: on-failure
      update_config:
        parallelism: 3
        delay: 10s
    networks:
      - scraps
    volumes:
      - ../data/api:/usr/app/data

networks:
  scraps:
    driver: bridge