export const enum Environment {
    API_PORT = 'API_PORT',
    NODE_ENV = 'NODE_ENV',
    SLEEP_TIME_SECONDS = 'SLEEP_TIME_SECONDS',
    SENDER_EMAIL = 'SENDER_EMAIL',
    SENDER_PASSWORD = 'SENDER_PASSWORD',
    RECEIVER_EMAILS = 'RECEIVER_EMAILS',

    ROBOTSTXT_OBEY = 'ROBOTSTXT_OBEY',
    CONCURRENT_REQUESTS = 'CONCURRENT_REQUESTS',
    DOWNLOAD_DELAY = 'DOWNLOAD_DELAY',

    DISCORD_TOKEN = 'DISCORD_TOKEN',
}
